const STORAGE_KEY = "chaw-lang";

const phrases = {
    en: {
        chawHome: "Chaw home",
        home: "Home",
        discover: "Discover",
        dashboard: "Dashboard",
        signIn: "Sign in",
        entryTitle: "Welcome to Chaw",
        entryLead: "Sign in, or join as a guest to look around and order.",
        joinAsGuest: "Join as a guest",
        anonymousOff: "Anonymous sign-in is turned off. In Firebase, open Authentication, then Sign-in method, and turn on Anonymous.",
        guestName: "Customer name",
        guestPhone: "Phone",
        guestAddress: "Delivery address",
        guestDetailsFirst: "Add your name, phone, and delivery address, and turn location on, before you place the order.",
        guestTurnLocationOn: "Turn location on so the driver can open your pin.",
        guestPinSaved: "Your map pin is saved. You can still edit the address.",
        yourAccount: "Your account",
        account: "Account",
        accountCount: "Account ({count})",
        cart: "Cart",
        cartCount: "Cart ({count})",
        titleHome: "Chaw — Discover What's Around You",
        titleSignIn: "Sign in — Chaw",
        titleDiscover: "Discover — Chaw",
        titleCart: "Cart — Chaw",
        titleProduct: "Product — Chaw",
        titleAccount: "Account — Chaw",
        titleDashboard: "Dashboard — Chaw",
        heroTitle: "Discover what's <span>around you.</span>",
        heroText: "Chaw connects people with local businesses, products and places worth discovering. Everything you need, closer than you think.",
        exploreChaw: "Explore Chaw",
        theCollection: "The collection",
        searchPlaceholder: "Search products or stores",
        everythingLocal: "Everything local.",
        featureDiscover: "🛍 Discover",
        featureDiscoverText: "Find products, stores and services around you without wasting time searching.",
        featureBusinesses: "🏪 Local Businesses",
        featureBusinessesText: "Businesses can showcase what they offer and reach more customers through Chaw.",
        featureNear: "📍 Near You",
        featureNearText: "Explore what's available in your city and discover businesses you didn't know existed.",
        footer: "© 2026 Chaw. All rights reserved.",
        signInHeading: "Sign in",
        signInLead: "Type your email and password. You can also use Google or Facebook.",
        emailAddress: "Email address",
        password: "Password",
        createAccount: "Create account",
        login: "Log in",
        continueGoogle: "Sign in with Google",
        openingGoogle: "Opening Google…",
        continueFacebook: "Sign in with Facebook",
        openingFacebook: "Opening Facebook…",
        facebookClosed: "Facebook sign-in was closed.",
        facebookPopupBlocked: "The Facebook window was blocked. Allow popups for this site, then try again.",
        facebookWrongMethod: "This email already uses another sign-in on Chaw. Sign in with email, or use Forgot password.",
        facebookUnauthorized: "Facebook sign-in is not turned on for this address yet.",
        facebookOff: "Turn on Facebook sign-in in Firebase, then try again.",
        forgotPassword: "Forgot password",
        needAccount: "New here? Create an account",
        haveAccount: "Already have an account? Sign in",
        or: "or",
        createHeading: "Create an account",
        createLead: "Type your email and a password of at least 6 characters. You can also use Google or Facebook.",
        resetSent: "Check your email. We sent a link to choose a new password.",
        enterEmailFirst: "Type your email first.",
        wrongEmailOrPassword: "That email or password is not the one saved on Chaw. A Gmail password is separate. Press Forgot password, or use Google or Facebook.",
        signInUnauthorized: "Sign in is not turned on for this website address yet.",
        enterRealEmail: "Type a real email address.",
        emailAlreadyUsed: "That email already has an account. Sign in instead.",
        passwordTooShort: "Use at least 6 characters.",
        enterPassword: "Type a password.",
        tooManyTries: "Too many tries. Wait a moment, then try again.",
        googleClosed: "Google sign-in was closed.",
        googlePopupBlocked: "The Google window was blocked. Allow popups for this site, then try again.",
        googleWrongMethod: "This Gmail already uses a password on Chaw. Sign in with email, or use Forgot password.",
        googleUnauthorized: "Google sign-in is not turned on for this address yet.",
        checkConnection: "Check your internet connection and try again.",
        couldNotSignIn: "Could not sign in. Try again.",
        googleOff: "Turn on Google sign-in in Firebase, then try again.",
        discoverHeading: "Discover",
        cartHeading: "Cart",
        editDetails: "Edit your details",
        howToPay: "How do you want to pay?",
        payOnDelivery: "Pay on delivery",
        payByCard: "Pay by card",
        payByCardNote: "Pay by card opens the store’s payment link. Chaw does not ask for your card number.",
        placeOrder: "Place order",
        yourOrders: "Your orders",
        backToDiscover: "Back to discover",
        editYourPieces: "Edit your pieces",
        editPiecesHelp: "Press Edit on a piece. Change it on the right, then press Save changes.",
        allowOrderAlerts: "Allow order alerts",
        logOut: "Log out",
        storeKicker: "Store",
        yourDetails: "Your details",
        displayName: "Customer name",
        storeName: "Store name",
        phone: "Phone",
        phoneNumber: "Phone number",
        deliveryLocation: "Delivery location",
        streetPlaceholder: "Street, area, city",
        deliveryHint: "The store uses this address so the delivery knows where to go.",
        profilePhoto: "Profile photo",
        storePhoto: "Store photo",
        storeContact: "Store contact",
        area: "Area",
        areaOrCity: "Area or city",
        whatsappNumber: "WhatsApp number",
        whatsappHint: "Customers see a WhatsApp button on your pieces. Include the country code.",
        driverWhatsapp: "Driver WhatsApp",
        driverWhatsappHint: "This number receives the address when you send an order. Include the country code.",
        cardPayments: "Card payments",
        customersCanPayByCard: "Customers can pay by card",
        cardPaymentLink: "Card payment link",
        httpsPlaceholder: "https://",
        cardLinkHint: "Paste the link where customers pay. Chaw never stores card numbers.",
        save: "Save",
        orders: "Orders",
        addAPiece: "Add a piece",
        chooseFilters: "Pick tags from each section, such as Size or Color.",
        pieceName: "Piece name",
        nameInArabic: "Name in Arabic",
        nameInKurdish: "Name in Kurdish",
        priceIqd: "Price (IQD)",
        stock: "Stock",
        description: "Description",
        descriptionInArabic: "Description in Arabic",
        descriptionInKurdish: "Description in Kurdish",
        photo: "Photo",
        publish: "Publish",
        cancel: "Cancel",
        admin: "Admin",
        adminOnly: "Only your admin account can see these settings.",
        filterWords: "Filter words",
        filterWordsHelp: "Add the English word, then Arabic and Kurdish. Choose a section such as Size or Color.",
        filterWord: "Filter word",
        addFilterWord: "Add filter word",
        businessAccounts: "Business accounts",
        businessAccountsHelp: "The account must already be signed up. Choose its category, then it can publish in that category.",
        accountEmail: "Account email",
        chooseCategory: "Choose a category",
        makeBusiness: "Make business",
        publicProducts: "Public products",
        publicProductsHelp: "Hide a product if it should leave Discover.",
        yourStore: "Your store",
        category: "Category",
        acceptCardPayments: "Accept card payments",
        cardPaymentLinkHttps: "Card payment link, https://",
        cardNeverSees: "Chaw never sees the card. Customers pay on the link you paste.",
        saveStore: "Save store",
        addProduct: "Add Product",
        productName: "Product name",
        stockQuantity: "Stock quantity",
        filters: "Filters",
        productPhoto: "Product photo",
        publishProduct: "Publish Product",
        sales: "Sales",
        thisMonthZero: "This month: 0",
        allSalesZero: "All sales: 0",
        myProducts: "My Products",
        chooseFilterWord: "Choose a filter word",
        noFilterWordsYet: "The admin has not added filter words yet.",
        photoTooLarge: "Photo is still too large. Choose a smaller one.",
        couldNotReadPhoto: "Could not read the photo.",
        chooseImageFile: "Please choose an image file.",
        imageUnder5: "Image must be under 5 MB.",
        chooseImageUnder5: "Choose an image under 5 MB.",
        mustBeLoggedIn: "You must be logged in to publish a product.",
        fillProductFields: "Please fill in all product fields.",
        productUpdated: "Product updated.",
        saveStoreBeforePublishing: "Save your store name before publishing.",
        chooseOneFilter: "Choose at least one filter for this product.",
        productPublished: "Product published successfully!",
        pleaseLogInProducts: "Please log in to see your products.",
        noProductsPublished: "You haven't published any products yet.",
        quantitySold: "Quantity sold",
        edit: "Edit",
        recordSale: "Record sale",
        delete: "Delete",
        stockLabel: "Stock: {stock}",
        enterWholeNumber: "Enter a whole number of items sold.",
        cannotSellMore: "You cannot sell more than the stock you have.",
        saleRecorded: "Sale recorded.",
        deleteThisProduct: "Delete this product?",
        productDeleted: "Product deleted.",
        couldNotLoadProducts: "Could not load products.",
        thisMonth: "This month: {amount}",
        allSales: "All sales: {amount}",
        noSalesYet: "No sales recorded yet.",
        couldNotLoadSales: "Could not load sales.",
        remove: "Remove",
        noFilterWords: "No filter words yet.",
        noBusinessAccounts: "No business accounts yet.",
        businessRemoved: "Business access removed.",
        everyBusinessNamed: "Every business has a store name.",
        hasNotSavedStore: "{name} has not saved a store name.",
        noProductsYet: "No products yet.",
        show: "Show",
        hide: "Hide",
        productPublicAgain: "Product is public again.",
        productHidden: "Product hidden from Discover.",
        saveStoreThenPublish: "Save the store name, then publish from your account.",
        publishingAs: "Publishing as {name}.",
        typeFilterFirst: "Type a filter word first.",
        filterExists: "That filter word already exists.",
        filterWord: "Filter word",
        filterAlreadyInSection: "{word} is already under {section}.",
        filterAdded: "Filter word added.",
        typeEmailCategory: "Type the email and choose a category.",
        adminStaysAdmin: "The admin account stays the admin.",
        noAccountEmail: "No signed-up account uses that email yet.",
        canPublishIn: "{email} can publish in {category}.",
        enterTheStoreName: "Enter the store name.",
        adminMustGiveCategory: "The admin has to give this account a category.",
        cardMustHttps: "The card link must start with https://",
        cardLinkHttp: "The card link must start with http:// or https://",
        enterStoreName: "Enter the store name.",
        enterDisplayName: "Enter a display name.",
        storeSaved: "Store saved.",
        accountSaved: "Account saved.",
        detailsSavedPiecesLater: "Your details are saved. Publish the database rules so your pieces update too.",
        saveStoreFirst: "Save the store name first.",
        enterNamePrice: "Enter the name, price, and description.",
        enterStock: "Enter the stock.",
        chooseFilter: "Choose at least one filter.",
        sectionSize: "Size",
        sectionColor: "Color",
        sectionType: "Type",
        sectionOther: "Other",
        chooseSection: "Choose a section",
        newSection: "New section",
        sectionName: "Section name",
        chooseSectionFirst: "Choose a section first.",
        sectionSaveDenied: "Publish the database rules so a tag can move into a section.",
        wordEnglish: "English",
        wordArabic: "Arabic",
        wordKurdish: "Kurdish",
        sectionEnglish: "Section in English",
        sectionArabic: "Section in Arabic",
        sectionKurdish: "Section in Kurdish",
        browseBy: "Browse",
        jumpPieces: "Pieces",
        jumpOrders: "Orders",
        jumpAdd: "Add a piece",
        jumpDetails: "Details",
        saveNeedsRules: "Publish the database rules, then try again.",
        pieceUpdated: "Piece updated.",
        publishedIn: "Published in {filters}.",
        noPiecesYet: "You have not published any pieces yet.",
        piecePhoto: "Piece photo",
        piece: "Piece",
        inStockLabel: "In stock: {stock}",
        editThisPiece: "Edit this piece",
        saveChanges: "Save changes",
        deleteThisPiece: "Delete this piece?",
        couldNotLoadPieces: "Could not load your pieces.",
        all: "All",
        nothingMatches: "Nothing matches that search.",
        closestMatches: "Closest to your search",
        nothingInCategory: "Nothing in this category yet.",
        putInCart: "Put in the cart",
        chooseOptions: "Choose color and size",
        chooseColorAndSize: "Choose a color and a size.",
        chooseColorFirst: "Choose a color.",
        chooseSizeFirst: "Choose a size.",
        signInToBuy: "Sign in to buy",
        store: "Store",
        product: "Product",
        callStore: "Call store",
        whatsapp: "WhatsApp",
        whatsappHello: "Hello, I want {product} from {store}.",
        whatsappCard: "I want to pay by card for {product}.",
        cardContact: "This store accepts card payments. Contact the store to pay.",
        productMissing: "This product could not be found.",
        productUnavailable: "This product is not available.",
        productOpenFailed: "Could not open this product.",
        inStock: "In stock: {stock}",
        signInToBuyPeriod: "Sign in to buy.",
        outOfStock: "Out of stock.",
        onlyLeft: "Only {stock} left.",
        addedToCart: "Added to cart.",
        cartEmpty: "Your cart is empty.",
        pieceWord: "piece",
        piecesWord: "pieces",
        totalLine: "{count} {pieces} · Total {amount}",
        clothesLine: "Clothes {amount}",
        clothesCardLine: "Clothes {amount}. Pay the store by its card link.",
        deliveryLine: "Delivery {amount}",
        payDriverDoor: "Pay the driver at the door {amount}",
        driverFees: "\nClothes: {clothes}\nDelivery: {delivery}\nCollect in cash: {cash}",
        signInToBuyLocation: "Sign in to buy. Your delivery location is saved on your account.",
        deliverTo: "Deliver to: {location}",
        addLocationBefore: "Add a delivery location on your account before you place the order.",
        noOrders: "No orders yet.",
        signInToSeeOrders: "Sign in to see orders you have placed.",
        statusLine: "Status: {status}",
        ordersAfterRules: "Orders will show after the new database rules are published.",
        newOrderFrom: "New order from {name}. Deliver to {location}.",
        aCustomer: "a customer",
        theirSavedAddress: "their saved address",
        newOrdersWaiting: "{count} new orders are waiting.",
        openOrders: "Open orders",
        markSeen: "Mark seen",
        newChawOrder: "New Chaw order",
        aCustomerCap: "A customer",
        theirAddress: "their address",
        orderedDeliver: "{name} ordered {items}. Deliver to {location}.",
        onTheWay: "On the way",
        delivered: "Delivered",
        statusNew: "New",
        statusCancelled: "Cancelled",
        cancelOrder: "Cancel order",
        customerNameLine: "Customer name: {name}",
        sizeLine: "Size: {size}",
        colorLine: "Color: {color}",
        quantityLine: "Quantity: {count}",
        priceLine: "Price: {price}",
        couldNotCancel: "Could not cancel that order.",
        markDelivered: "Mark delivered",
        customer: "Customer",
        phoneLine: "Phone: {phone}",
        yourCartEmpty: "Your cart is empty.",
        saveLocationFirst: "Open your account and save a delivery location first.",
        savePhoneFirst: "Open your account and save a phone number first.",
        addPhoneBefore: "Add a phone number on your account before you place the order.",
        openInMaps: "Open in Maps",
        callCustomer: "Call",
        sendToDriver: "Send to driver",
        addDriverNumber: "Add the driver WhatsApp number under Store contact.",
        noPhone: "No phone",
        driverOrder: "New delivery\n{name}\nPhone: {phone}\nAddress: {location}\n{pin}{items}\n{payment}{fees}",
        shareLocationText: "Open your location so the store can send the driver to the exact place.",
        useMyLocation: "Use my location",
        notNow: "Not now",
        findingLocation: "Finding your location…",
        locationSaved: "Exact location saved. The store can send this pin to the driver.",
        locationDenied: "Location stayed off. Turn it on in the browser, then try again.",
        locationFailed: "Could not read your location. Try again.",
        locationUnsupported: "This browser cannot share a location.",
        pinLine: "Pin: {url}",
        exactPinSaved: "Exact pin saved.",
        pieceHasNoStore: "One piece has no store, so it cannot be ordered.",
        aPiece: "A piece",
        noLongerAvailable: "{name} is no longer available.",
        onlyLeftOf: "Only {stock} left of {name}.",
        theStore: "the store",
        orderSentCard: "Order sent. Pay by card with the store.",
        orderSentDelivery: "Order sent. Pay on delivery. The store has your location.",
        payStoreByCard: "Pay {store} by card",
        publishRulesStock: "Publish the new database rules so the order can lower the stock, then try again.",
        couldNotPlaceOrder: "Could not place the order.",
        inCategory: " in {category}",
        noCategoryYet: " — no category yet",
        hiddenTag: " (hidden)"
    },
    ar: {
        chawHome: "صفحة تشاو",
        home: "الرئيسية",
        discover: "اكتشف",
        dashboard: "لوحة التحكم",
        signIn: "تسجيل الدخول",
        entryTitle: "أهلاً بك في چاو",
        entryLead: "سجّل الدخول، أو ادخل كضيف لتتسوق وتطلب.",
        joinAsGuest: "الدخول كضيف",
        anonymousOff: "تسجيل الدخول المجهول غير مفعّل. في Firebase افتح Authentication ثم Sign-in method وفعّل Anonymous.",
        guestName: "اسم الزبون",
        guestPhone: "الهاتف",
        guestAddress: "عنوان التوصيل",
        guestDetailsFirst: "أضف اسمك ورقم هاتفك وعنوان التوصيل، وشغّل الموقع، قبل إرسال الطلب.",
        guestTurnLocationOn: "شغّل الموقع حتى يفتح السائق موقعك على الخريطة.",
        guestPinSaved: "تم حفظ موقعك على الخريطة. يمكنك تعديل العنوان.",
        yourAccount: "حسابك",
        account: "الحساب",
        accountCount: "الحساب ({count})",
        cart: "السلة",
        cartCount: "السلة ({count})",
        titleHome: "تشاو — اكتشف ما حولك",
        titleSignIn: "تسجيل الدخول — تشاو",
        titleDiscover: "اكتشف — تشاو",
        titleCart: "السلة — تشاو",
        titleProduct: "منتج — تشاو",
        titleAccount: "الحساب — تشاو",
        titleDashboard: "لوحة التحكم — تشاو",
        heroTitle: "اكتشف ما <span>حولك.</span>",
        heroText: "تشاو يربط الناس بالمتاجر المحلية والمنتجات والأماكن التي تستحق الاكتشاف. كل ما تحتاجه أقرب مما تظن.",
        exploreChaw: "استكشف تشاو",
        theCollection: "المجموعة",
        searchPlaceholder: "ابحث عن منتج أو متجر",
        everythingLocal: "كل شيء محلي.",
        featureDiscover: "🛍 اكتشف",
        featureDiscoverText: "اعثر على المنتجات والمتاجر والخدمات من حولك من غير بحث طويل.",
        featureBusinesses: "🏪 متاجر محلية",
        featureBusinessesText: "يمكن للمتاجر عرض ما تقدمه والوصول إلى زبائن أكثر عبر تشاو.",
        featureNear: "📍 بالقرب منك",
        featureNearText: "تعرّف على ما هو متوفر في مدينتك وعلى متاجر لم تكن تعرفها.",
        footer: "© 2026 تشاو. جميع الحقوق محفوظة.",
        signInHeading: "تسجيل الدخول",
        signInLead: "اكتب بريدك وكلمة المرور. يمكنك أيضاً استخدام Google أو Facebook.",
        emailAddress: "البريد الإلكتروني",
        password: "كلمة المرور",
        createAccount: "إنشاء حساب",
        login: "سجّل الدخول",
        continueGoogle: "تسجيل الدخول بحساب Google",
        openingGoogle: "جارٍ فتح Google…",
        continueFacebook: "تسجيل الدخول بحساب Facebook",
        openingFacebook: "جارٍ فتح Facebook…",
        facebookClosed: "أُغلق تسجيل الدخول بفيسبوك.",
        facebookPopupBlocked: "نافذة Facebook محجوبة. اسمح بالنوافذ المنبثقة لهذا الموقع، ثم أعد المحاولة.",
        facebookWrongMethod: "هذا البريد يستخدم طريقة أخرى هنا. سجّل الدخول بالبريد، أو استخدم نسيت كلمة المرور.",
        facebookUnauthorized: "تسجيل الدخول بـ Facebook غير مفعّل لهذا العنوان بعد.",
        facebookOff: "فعّل تسجيل الدخول بفيسبوك في فايربيس، ثم أعد المحاولة.",
        forgotPassword: "نسيت كلمة المرور",
        needAccount: "جديد هنا؟ أنشئ حساباً",
        haveAccount: "لديك حساب؟ سجّل الدخول",
        or: "أو",
        createHeading: "إنشاء حساب",
        createLead: "اكتب بريدك وكلمة مرور من 6 أحرف على الأقل. يمكنك أيضاً استخدام Google أو Facebook.",
        resetSent: "تحقق من بريدك. أرسلنا رابطاً لاختيار كلمة مرور جديدة.",
        enterEmailFirst: "اكتب بريدك أولاً.",
        wrongEmailOrPassword: "هذا البريد أو كلمة المرور ليست المحفوظة في تشاو. كلمة مرور Gmail مختلفة. اضغط نسيت كلمة المرور، أو استخدم Google أو Facebook.",
        signInUnauthorized: "تسجيل الدخول غير مفعّل لهذا العنوان بعد.",
        enterRealEmail: "اكتب بريداً حقيقياً.",
        emailAlreadyUsed: "هذا البريد له حساب. سجّل الدخول.",
        passwordTooShort: "استخدم 6 أحرف على الأقل.",
        enterPassword: "اكتب كلمة المرور.",
        tooManyTries: "محاولات كثيرة. انتظر قليلاً ثم أعد المحاولة.",
        googleClosed: "أُغلق تسجيل الدخول بغوغل.",
        googlePopupBlocked: "نافذة Google محجوبة. اسمح بالنوافذ المنبثقة لهذا الموقع، ثم أعد المحاولة.",
        googleWrongMethod: "هذا البريد يستخدم كلمة مرور هنا. سجّل الدخول بالبريد، أو استخدم نسيت كلمة المرور.",
        googleUnauthorized: "تسجيل الدخول بـ Google غير مفعّل لهذا العنوان بعد.",
        checkConnection: "تحقق من الإنترنت ثم أعد المحاولة.",
        couldNotSignIn: "تعذر تسجيل الدخول. أعد المحاولة.",
        googleOff: "فعّل تسجيل الدخول بغوغل في فايربيس، ثم أعد المحاولة.",
        discoverHeading: "اكتشف",
        cartHeading: "السلة",
        editDetails: "تعديل بياناتك",
        howToPay: "كيف تريد الدفع؟",
        payOnDelivery: "الدفع عند الاستلام",
        payByCard: "الدفع بالبطاقة",
        payByCardNote: "الدفع بالبطاقة يفتح رابط دفع المتجر. تشاو لا يطلب رقم بطاقتك.",
        placeOrder: "إرسال الطلب",
        yourOrders: "طلباتك",
        backToDiscover: "العودة إلى الاستكشاف",
        editYourPieces: "تعديل قطعك",
        editPiecesHelp: "اضغط تعديل على قطعة. غيّرها في الجهة المقابلة، ثم اضغط حفظ التغييرات.",
        allowOrderAlerts: "السماح بتنبيهات الطلبات",
        logOut: "تسجيل الخروج",
        storeKicker: "متجر",
        yourDetails: "بياناتك",
        displayName: "اسم الزبون",
        storeName: "اسم المتجر",
        phone: "الهاتف",
        phoneNumber: "رقم الهاتف",
        deliveryLocation: "عنوان التوصيل",
        streetPlaceholder: "الشارع، المنطقة، المدينة",
        deliveryHint: "يستخدم المتجر هذا العنوان ليعرف المندوب إلى أين يذهب.",
        profilePhoto: "صورة الحساب",
        storePhoto: "صورة المتجر",
        storeContact: "التواصل مع المتجر",
        area: "المنطقة",
        areaOrCity: "المنطقة أو المدينة",
        whatsappNumber: "رقم واتساب",
        whatsappHint: "يرى الزبائن زر واتساب على قطعك. أضف رمز الدولة.",
        driverWhatsapp: "واتساب السائق",
        driverWhatsappHint: "هذا الرقم يستلم العنوان عند إرسال الطلب. أضف رمز الدولة.",
        cardPayments: "الدفع بالبطاقة",
        customersCanPayByCard: "يمكن للزبائن الدفع بالبطاقة",
        cardPaymentLink: "رابط الدفع بالبطاقة",
        httpsPlaceholder: "https://",
        cardLinkHint: "الصق الرابط الذي يدفع منه الزبائن. تشاو لا يحفظ أرقام البطاقات.",
        save: "حفظ",
        orders: "الطلبات",
        addAPiece: "إضافة قطعة",
        chooseFilters: "اختر الوسوم من كل قسم، مثل المقاس أو اللون.",
        pieceName: "اسم القطعة",
        nameInArabic: "الاسم بالعربية",
        nameInKurdish: "الاسم بالكردية",
        priceIqd: "السعر (IQD)",
        stock: "الكمية",
        description: "الوصف",
        descriptionInArabic: "الوصف بالعربية",
        descriptionInKurdish: "الوصف بالكردية",
        photo: "صورة",
        publish: "نشر",
        cancel: "إلغاء",
        admin: "الإدارة",
        adminOnly: "حساب الإدارة فقط يرى هذه الإعدادات.",
        filterWords: "كلمات التصفية",
        filterWordsHelp: "أضف الكلمة بالإنجليزية، ثم بالعربية والكردية. اختر قسماً مثل المقاس أو اللون.",
        filterWord: "كلمة تصفية",
        addFilterWord: "إضافة كلمة",
        businessAccounts: "حسابات المتاجر",
        businessAccountsHelp: "يجب أن يكون الحساب مسجلاً من قبل. اختر تصنيفه، ثم يمكنه النشر في ذلك التصنيف.",
        accountEmail: "بريد الحساب",
        chooseCategory: "اختر تصنيفاً",
        makeBusiness: "تحويل إلى متجر",
        publicProducts: "المنتجات الظاهرة",
        publicProductsHelp: "أخفِ المنتج إذا أردت إزالته من صفحة الاستكشاف.",
        yourStore: "متجرك",
        category: "التصنيف",
        acceptCardPayments: "قبول الدفع بالبطاقة",
        cardPaymentLinkHttps: "رابط الدفع بالبطاقة، https://",
        cardNeverSees: "تشاو لا يرى البطاقة. يدفع الزبائن عبر الرابط الذي تلصقه.",
        saveStore: "حفظ المتجر",
        addProduct: "إضافة منتج",
        productName: "اسم المنتج",
        stockQuantity: "الكمية المتوفرة",
        filters: "التصفية",
        productPhoto: "صورة المنتج",
        publishProduct: "نشر المنتج",
        sales: "المبيعات",
        thisMonthZero: "هذا الشهر: 0",
        allSalesZero: "كل المبيعات: 0",
        myProducts: "منتجاتي",
        chooseFilterWord: "اختر كلمة تصفية",
        noFilterWordsYet: "لم يضف المدير كلمات تصفية بعد.",
        photoTooLarge: "الصورة ما زالت كبيرة. اختر صورة أصغر.",
        couldNotReadPhoto: "تعذر قراءة الصورة.",
        chooseImageFile: "يرجى اختيار ملف صورة.",
        imageUnder5: "يجب أن تكون الصورة أقل من 5 ميغابايت.",
        chooseImageUnder5: "اختر صورة أقل من 5 ميغابايت.",
        mustBeLoggedIn: "يجب تسجيل الدخول لنشر منتج.",
        fillProductFields: "يرجى تعبئة كل حقول المنتج.",
        productUpdated: "تم تحديث المنتج.",
        saveStoreBeforePublishing: "احفظ اسم المتجر قبل النشر.",
        chooseOneFilter: "اختر تصفية واحدة على الأقل لهذا المنتج.",
        productPublished: "تم نشر المنتج.",
        pleaseLogInProducts: "سجّل الدخول لترى منتجاتك.",
        noProductsPublished: "لم تنشر أي منتج بعد.",
        quantitySold: "الكمية المباعة",
        edit: "تعديل",
        recordSale: "تسجيل بيع",
        delete: "حذف",
        stockLabel: "الكمية: {stock}",
        enterWholeNumber: "أدخل عدداً صحيحاً للقطع المباعة.",
        cannotSellMore: "لا يمكنك بيع أكثر من الكمية المتوفرة.",
        saleRecorded: "تم تسجيل البيع.",
        deleteThisProduct: "حذف هذا المنتج؟",
        productDeleted: "تم حذف المنتج.",
        couldNotLoadProducts: "تعذر تحميل المنتجات.",
        thisMonth: "هذا الشهر: {amount}",
        allSales: "كل المبيعات: {amount}",
        noSalesYet: "لا مبيعات مسجلة بعد.",
        couldNotLoadSales: "تعذر تحميل المبيعات.",
        remove: "إزالة",
        noFilterWords: "لا كلمات تصفية بعد.",
        noBusinessAccounts: "لا حسابات متاجر بعد.",
        businessRemoved: "أُزيلت صلاحية المتجر.",
        everyBusinessNamed: "كل المتاجر لديها اسم.",
        hasNotSavedStore: "{name} لم يحفظ اسم المتجر.",
        noProductsYet: "لا منتجات بعد.",
        show: "إظهار",
        hide: "إخفاء",
        productPublicAgain: "المنتج ظاهر من جديد.",
        productHidden: "أُخفي المنتج من صفحة الاستكشاف.",
        saveStoreThenPublish: "احفظ اسم المتجر، ثم انشر من حسابك.",
        publishingAs: "النشر باسم {name}.",
        typeFilterFirst: "اكتب كلمة تصفية أولاً.",
        filterExists: "كلمة التصفية هذه موجودة.",
        filterWord: "كلمة التصفية",
        filterAlreadyInSection: "{word} موجود تحت {section}.",
        filterAdded: "أُضيفت كلمة التصفية.",
        typeEmailCategory: "اكتب البريد واختر تصنيفاً.",
        adminStaysAdmin: "حساب الإدارة يبقى حساب إدارة.",
        noAccountEmail: "لا يوجد حساب مسجل بهذا البريد بعد.",
        canPublishIn: "{email} يمكنه النشر في {category}.",
        enterTheStoreName: "أدخل اسم المتجر.",
        adminMustGiveCategory: "يجب أن يعطي المدير هذا الحساب تصنيفاً.",
        cardMustHttps: "يجب أن يبدأ رابط البطاقة بـ https://",
        cardLinkHttp: "يجب أن يبدأ رابط البطاقة بـ http:// أو https://",
        enterStoreName: "أدخل اسم المتجر.",
        enterDisplayName: "أدخل اسماً ظاهراً.",
        storeSaved: "تم حفظ المتجر.",
        accountSaved: "تم حفظ الحساب.",
        detailsSavedPiecesLater: "تم حفظ بياناتك. انشر قواعد قاعدة البيانات حتى تتحدث القطع أيضاً.",
        saveStoreFirst: "احفظ اسم المتجر أولاً.",
        enterNamePrice: "أدخل الاسم والسعر والوصف.",
        enterStock: "أدخل الكمية.",
        chooseFilter: "اختر تصفية واحدة على الأقل.",
        sectionSize: "المقاس",
        sectionColor: "اللون",
        sectionType: "النوع",
        sectionOther: "أخرى",
        chooseSection: "اختر قسماً",
        newSection: "قسم جديد",
        sectionName: "اسم القسم",
        chooseSectionFirst: "اختر قسماً أولاً.",
        sectionSaveDenied: "انشر قواعد قاعدة البيانات حتى يمكن نقل الوسم إلى قسم.",
        wordEnglish: "الإنجليزية",
        wordArabic: "العربية",
        wordKurdish: "الكردية",
        sectionEnglish: "اسم القسم بالإنجليزية",
        sectionArabic: "اسم القسم بالعربية",
        sectionKurdish: "اسم القسم بالكردية",
        browseBy: "تصفح",
        jumpPieces: "القطع",
        jumpOrders: "الطلبات",
        jumpAdd: "إضافة قطعة",
        jumpDetails: "البيانات",
        saveNeedsRules: "انشر قواعد قاعدة البيانات، ثم أعد المحاولة.",
        pieceUpdated: "تم تحديث القطعة.",
        publishedIn: "نُشر في {filters}.",
        noPiecesYet: "لم تنشر أي قطعة بعد.",
        piecePhoto: "صورة القطعة",
        piece: "قطعة",
        inStockLabel: "المتوفر: {stock}",
        editThisPiece: "تعديل هذه القطعة",
        saveChanges: "حفظ التغييرات",
        deleteThisPiece: "حذف هذه القطعة؟",
        couldNotLoadPieces: "تعذر تحميل قطعك.",
        all: "الكل",
        nothingMatches: "لا شيء يطابق هذا البحث.",
        closestMatches: "الأقرب إلى بحثك",
        nothingInCategory: "لا شيء في هذا التصنيف بعد.",
        putInCart: "أضف إلى السلة",
        chooseOptions: "اختر اللون والمقاس",
        chooseColorAndSize: "اختر لوناً ومقاساً.",
        chooseColorFirst: "اختر لوناً.",
        chooseSizeFirst: "اختر مقاساً.",
        signInToBuy: "سجّل الدخول للشراء",
        store: "متجر",
        product: "منتج",
        callStore: "اتصال بالمتجر",
        whatsapp: "واتساب",
        whatsappHello: "مرحباً، أريد {product} من {store}.",
        whatsappCard: "أريد الدفع بالبطاقة مقابل {product}.",
        cardContact: "هذا المتجر يقبل الدفع بالبطاقة. تواصل مع المتجر للدفع.",
        productMissing: "تعذر العثور على هذا المنتج.",
        productUnavailable: "هذا المنتج غير متوفر.",
        productOpenFailed: "تعذر فتح هذا المنتج.",
        inStock: "المتوفر: {stock}",
        signInToBuyPeriod: "سجّل الدخول للشراء.",
        outOfStock: "نفدت الكمية.",
        onlyLeft: "تبقّى {stock} فقط.",
        addedToCart: "أُضيف إلى السلة.",
        cartEmpty: "سلتك فارغة.",
        pieceWord: "قطعة",
        piecesWord: "قطع",
        totalLine: "{count} {pieces} · المجموع {amount}",
        clothesLine: "الملابس {amount}",
        clothesCardLine: "الملابس {amount}. ادفع للمتجر عبر رابط البطاقة.",
        deliveryLine: "التوصيل {amount}",
        payDriverDoor: "ادفع للسائق عند الباب {amount}",
        driverFees: "\nالملابس: {clothes}\nالتوصيل: {delivery}\nالنقد عند الباب: {cash}",
        signInToBuyLocation: "سجّل الدخول للشراء. عنوان التوصيل محفوظ في حسابك.",
        deliverTo: "التوصيل إلى: {location}",
        addLocationBefore: "أضف عنوان توصيل في حسابك قبل إرسال الطلب.",
        noOrders: "لا طلبات بعد.",
        signInToSeeOrders: "سجّل الدخول لترى الطلبات التي أرسلتها.",
        statusLine: "الحالة: {status}",
        ordersAfterRules: "ستظهر الطلبات بعد نشر قواعد قاعدة البيانات الجديدة.",
        newOrderFrom: "طلب جديد من {name}. أوصله إلى {location}.",
        aCustomer: "زبون",
        theirSavedAddress: "عنوانه المحفوظ",
        newOrdersWaiting: "{count} طلبات جديدة بانتظارك.",
        openOrders: "فتح الطلبات",
        markSeen: "تعليم كمقروء",
        newChawOrder: "طلب جديد على تشاو",
        aCustomerCap: "زبون",
        theirAddress: "عنوانه",
        orderedDeliver: "{name} طلب {items}. أوصله إلى {location}.",
        onTheWay: "في الطريق",
        delivered: "تم التوصيل",
        statusNew: "جديد",
        statusCancelled: "ملغى",
        cancelOrder: "إلغاء الطلب",
        customerNameLine: "اسم الزبون: {name}",
        sizeLine: "المقاس: {size}",
        colorLine: "اللون: {color}",
        quantityLine: "الكمية: {count}",
        priceLine: "السعر: {price}",
        couldNotCancel: "تعذر إلغاء هذا الطلب.",
        markDelivered: "تعليم كتم التوصيل",
        customer: "الزبون",
        phoneLine: "الهاتف: {phone}",
        yourCartEmpty: "سلتك فارغة.",
        saveLocationFirst: "افتح حسابك واحفظ عنوان التوصيل أولاً.",
        savePhoneFirst: "افتح حسابك واحفظ رقم هاتف أولاً.",
        addPhoneBefore: "أضف رقم هاتف في حسابك قبل إرسال الطلب.",
        openInMaps: "افتح في الخرائط",
        callCustomer: "اتصال",
        sendToDriver: "أرسل إلى السائق",
        addDriverNumber: "أضف رقم واتساب السائق في تواصل المتجر.",
        noPhone: "بدون هاتف",
        driverOrder: "توصيل جديد\n{name}\nالهاتف: {phone}\nالعنوان: {location}\n{pin}{items}\n{payment}{fees}",
        shareLocationText: "افتح موقعك حتى يرسل المتجر السائق إلى المكان بالضبط.",
        useMyLocation: "استخدم موقعي",
        notNow: "ليس الآن",
        findingLocation: "جارٍ تحديد موقعك…",
        locationSaved: "تم حفظ الموقع الدقيق. يستطيع المتجر إرسال هذه النقطة إلى السائق.",
        locationDenied: "بقي الموقع مغلقاً. شغّله من المتصفح ثم أعد المحاولة.",
        locationFailed: "تعذر قراءة موقعك. أعد المحاولة.",
        locationUnsupported: "هذا المتصفح لا يستطيع مشاركة الموقع.",
        pinLine: "الموقع: {url}",
        exactPinSaved: "تم حفظ الموقع الدقيق.",
        pieceHasNoStore: "قطعة بلا متجر، لذلك لا يمكن طلبها.",
        aPiece: "قطعة",
        noLongerAvailable: "{name} لم يعد متوفراً.",
        onlyLeftOf: "تبقّى {stock} فقط من {name}.",
        theStore: "المتجر",
        orderSentCard: "أُرسل الطلب. ادفع بالبطاقة مع المتجر.",
        orderSentDelivery: "أُرسل الطلب. الدفع عند الاستلام. المتجر لديه عنوانك.",
        payStoreByCard: "ادفع لـ {store} بالبطاقة",
        publishRulesStock: "انشر قواعد قاعدة البيانات الجديدة حتى ينقص المخزون مع الطلب، ثم أعد المحاولة.",
        couldNotPlaceOrder: "تعذر إرسال الطلب.",
        inCategory: " في {category}",
        noCategoryYet: " — بلا تصنيف بعد",
        hiddenTag: " (مخفي)"
    },
    ckb: {
        chawHome: "ماڵەوەی چاو",
        home: "سەرەکی",
        discover: "دۆزینەوە",
        dashboard: "داشبۆرد",
        signIn: "چوونەژوورەوە",
        entryTitle: "بەخێربێیت بۆ چاو",
        entryLead: "بچۆ ژوورەوە، یان وەک میوان بێوە تا بگەڕێیت و داواکاری بنێریت.",
        joinAsGuest: "وەک میوان بێوە",
        anonymousOff: "چوونەژوورەوەی نەناسراو کوژاوەتەوە. لە Firebase بکەرەوە Authentication، پاشان Sign-in method، و Anonymous چالاک بکە.",
        guestName: "ناوی کڕیار",
        guestPhone: "تەلەفۆن",
        guestAddress: "ناونیشانی گەیاندن",
        guestDetailsFirst: "پێش ناردنی داواکاری ناوت و تەلەفۆن و ناونیشان بنووسە و شوێنەکەت دابگیرسێنە.",
        guestTurnLocationOn: "شوێنەکەت دابگیرسێنە تا شۆفێرەکە پینەکە لە نەخشە بکاتەوە.",
        guestPinSaved: "پینی نەخشە پاشەکەوت کرا. دەتوانیت ناونیشانەکە بگۆڕیت.",
        yourAccount: "هەژمارەکەت",
        account: "هەژمار",
        accountCount: "هەژمار ({count})",
        cart: "سەبەتە",
        cartCount: "سەبەتە ({count})",
        titleHome: "چاو — ئەوەی لە دەوروبەرتە بدۆزەرەوە",
        titleSignIn: "چوونەژوورەوە — چاو",
        titleDiscover: "دۆزینەوە — چاو",
        titleCart: "سەبەتە — چاو",
        titleProduct: "کاڵا — چاو",
        titleAccount: "هەژمار — چاو",
        titleDashboard: "داشبۆرد — چاو",
        heroTitle: "بدۆزەرەوە ئەوەی <span>لە دەوروبەرتە.</span>",
        heroText: "چاو خەڵک بە فرۆشگا ناوخۆییەکان و کاڵا و شوێنەکانەوە دەبەستێتەوە. هەموو ئەوەی پێویستتە، لەوەی بیری لێ دەکەیتەوە نزیکترە.",
        exploreChaw: "چاو بگەڕێ",
        theCollection: "کۆکراوە",
        searchPlaceholder: "گەڕان بۆ کاڵا یان فرۆشگا",
        everythingLocal: "هەمووی ناوخۆیی.",
        featureDiscover: "🛍 دۆزینەوە",
        featureDiscoverText: "کاڵا و فرۆشگا و خزمەتگوزارییەکانی دەوروبەرت بدۆزەرەوە بەبێ گەڕانی درێژ.",
        featureBusinesses: "🏪 فرۆشگا ناوخۆییەکان",
        featureBusinessesText: "فرۆشگاکان دەتوانن ئەوەی پێشکەشی دەکەن پیشان بدەن و لە ڕێگەی چاوەوە بگەنە کڕیاری زیاتر.",
        featureNear: "📍 لە نزیکت",
        featureNearText: "بزانە لە شارەکەتدا چی هەیە و فرۆشگایەک بدۆزەرەوە کە پێشتر نەتدهزانی.",
        footer: "© 2026 چاو. هەموو مافەکان پارێزراون.",
        signInHeading: "چوونەژوورەوە",
        signInLead: "ئیمەیڵ و وشەی نهێنی بنووسە. دەتوانیت Google یان Facebookیش بەکاربهێنیت.",
        emailAddress: "ئیمەیڵ",
        password: "وشەی نهێنی",
        createAccount: "دروستکردنی هەژمار",
        login: "بچۆ ژوورەوە",
        continueGoogle: "چوونەژوورەوە بە Google",
        openingGoogle: "Google دەکرێتەوە…",
        continueFacebook: "چوونەژوورەوە بە Facebook",
        openingFacebook: "Facebook دەکرێتەوە…",
        facebookClosed: "چوونەژوورەوەی فەیسبووک داخرا.",
        facebookPopupBlocked: "پەنجەرەی Facebook ڕێگری لێکرا. پەنجەرەی سەرهەڵدەر بۆ ئەم ماڵپەڕە ڕێگە بدە، پاشان دووبارە هەوڵبدە.",
        facebookWrongMethod: "ئەم ئیمەیڵە ڕێگەیەکی تری چوونەژوورەوەی لەسەر چاو هەیە. بە ئیمەیڵ بچۆ ژوورەوە، یان وشەی نهێنیم لەبیرچووە بەکاربهێنە.",
        facebookUnauthorized: "چوونەژوورەوە بە Facebook بۆ ئەم ناونیشانە هێشتا دانەگیرساوە.",
        facebookOff: "چوونەژوورەوەی فەیسبووک لە فایەربەیس دابگیرسێنە، پاشان دووبارە هەوڵبدە.",
        forgotPassword: "وشەی نهێنیم لەبیرچووە",
        needAccount: "نوێیت؟ هەژمار دروست بکە",
        haveAccount: "هەژمارت هەیە؟ بچۆ ژوورەوە",
        or: "یان",
        createHeading: "دروستکردنی هەژمار",
        createLead: "ئیمەیڵ و وشەیەکی نهێنی بنووسە کە لانیکەم ٦ پیت بێت. دەتوانیت Google یان Facebookیش بەکاربهێنیت.",
        resetSent: "ئیمەیڵەکەت بپشکنە. بەستەرێکمان نارد بۆ هەڵبژاردنی وشەیەکی نهێنی نوێ.",
        enterEmailFirst: "سەرەتا ئیمەیڵەکەت بنووسە.",
        wrongEmailOrPassword: "ئەم ئیمەیڵە یان وشەی نهێنییە لە چاو پاشەکەوت نەکراوە. وشەی نهێنی Gmail جیاوازە. وشەی نهێنیم لەبیرچووە دابگرە، یان Google یان Facebook بەکاربهێنە.",
        signInUnauthorized: "چوونەژوورەوە بۆ ئەم ناونیشانە هێشتا چالاک نییە.",
        enterRealEmail: "ئیمەیڵێکی ڕاست بنووسە.",
        emailAlreadyUsed: "ئەم ئیمەیڵە هەژماری هەیە. بچۆ ژوورەوە.",
        passwordTooShort: "لانیکەم ٦ پیت بەکاربهێنە.",
        enterPassword: "وشەی نهێنی بنووسە.",
        tooManyTries: "هەوڵی زۆر. کەمێک چاوەڕێ بکە، پاشان دووبارە هەوڵبدە.",
        googleClosed: "چوونەژوورەوەی گووگڵ داخرا.",
        googlePopupBlocked: "پەنجەرەی Google ڕێگری لێکرا. پەنجەرەی سەرهەڵدەر بۆ ئەم ماڵپەڕە ڕێگە بدە، پاشان دووبارە هەوڵبدە.",
        googleWrongMethod: "ئەم ئیمەیڵە وشەی نهێنی لەسەر چاو هەیە. بە ئیمەیڵ بچۆ ژوورەوە، یان وشەی نهێنیم لەبیرچووە بەکاربهێنە.",
        googleUnauthorized: "چوونەژوورەوە بە Google بۆ ئەم ناونیشانە هێشتا دانەگیرساوە.",
        checkConnection: "ئینتەرنێتەکەت بپشکنە و دووبارە هەوڵبدە.",
        couldNotSignIn: "نەتوانرا بچیتە ژوورەوە. دووبارە هەوڵبدە.",
        googleOff: "چوونەژوورەوەی گووگڵ لە فایەربەیس دابگیرسێنە، پاشان دووبارە هەوڵبدە.",
        discoverHeading: "دۆزینەوە",
        cartHeading: "سەبەتە",
        editDetails: "زانیارییەکانت دەستکاری بکە",
        howToPay: "دەتەوێت چۆن پارە بدەیت؟",
        payOnDelivery: "پارەدان لە کاتی گەیاندن",
        payByCard: "پارەدان بە کارت",
        payByCardNote: "پارەدان بە کارت بەستەری پارەدانی فرۆشگا دەکاتەوە. چاو ژمارەی کارتەکەت ناوێت.",
        placeOrder: "ناردنی داواکاری",
        yourOrders: "داواکارییەکانت",
        backToDiscover: "گەڕانەوە بۆ دۆزینەوە",
        editYourPieces: "پارچەکانت دەستکاری بکە",
        editPiecesHelp: "دەستکاری لەسەر پارچەیەک دابگرە. لە لای ڕاست بیگۆڕە، پاشان پاشەکەوتکردنی گۆڕانکارییەکان دابگرە.",
        allowOrderAlerts: "ڕێگەدان بە ئاگادارکردنەوەی داواکاری",
        logOut: "چوونەدەرەوە",
        storeKicker: "فرۆشگا",
        yourDetails: "زانیارییەکانت",
        displayName: "ناوی کڕیار",
        storeName: "ناوی فرۆشگا",
        phone: "تەلەفۆن",
        phoneNumber: "ژمارەی تەلەفۆن",
        deliveryLocation: "شوێنی گەیاندن",
        streetPlaceholder: "شەقام، ناوچە، شار",
        deliveryHint: "فرۆشگا ئەم ناونیشانە بەکاردەهێنێت بۆ ئەوەی گەیەنەر بزانێت بۆ کوێ دەڕوات.",
        profilePhoto: "وێنەی هەژمار",
        storePhoto: "وێنەی فرۆشگا",
        storeContact: "پەیوەندی فرۆشگا",
        area: "ناوچە",
        areaOrCity: "ناوچە یان شار",
        whatsappNumber: "ژمارەی واتساپ",
        whatsappHint: "کڕیار دوگمەی واتساپ لەسەر پارچەکانت دەبینێت. کۆدی وڵات بنووسە.",
        driverWhatsapp: "واتساپی گەیەنەر",
        driverWhatsappHint: "ئەم ژمارەیە ناونیشانەکە وەردەگرێت کاتێک داواکاری دەنێریت. کۆدی وڵات بنووسە.",
        cardPayments: "پارەدان بە کارت",
        customersCanPayByCard: "کڕیار دەتوانێت بە کارت پارە بدات",
        cardPaymentLink: "بەستەری پارەدان بە کارت",
        httpsPlaceholder: "https://",
        cardLinkHint: "ئەو بەستەرە بلکێنە کە کڕیار لێی پارە دەدات. چاو ژمارەی کارت هەڵناگرێت.",
        save: "پاشەکەوت",
        orders: "داواکارییەکان",
        addAPiece: "پارچەیەک زیاد بکە",
        chooseFilters: "تاگەکان لە هەر بەشێک هەڵبژێرە، وەک قەبارە یان ڕەنگ.",
        pieceName: "ناوی پارچە",
        nameInArabic: "ناو بە عەرەبی",
        nameInKurdish: "ناو بە کوردی",
        priceIqd: "نرخ (IQD)",
        stock: "بڕ",
        description: "وەسف",
        descriptionInArabic: "وەسف بە عەرەبی",
        descriptionInKurdish: "وەسف بە کوردی",
        photo: "وێنە",
        publish: "بڵاوکردنەوە",
        cancel: "پاشگەزبوونەوە",
        admin: "بەڕێوەبەر",
        adminOnly: "تەنها هەژماری بەڕێوەبەر ئەم ڕێکخستنانە دەبینێت.",
        filterWords: "وشەکانی پاڵاوتن",
        filterWordsHelp: "وشەکە بە ئینگلیزی بنووسە، پاشان بە عەرەبی و کوردی. بەشێک هەڵبژێرە وەک قەبارە یان ڕەنگ.",
        filterWord: "وشەی پاڵاوتن",
        addFilterWord: "زیادکردنی وشە",
        businessAccounts: "هەژماری فرۆشگا",
        businessAccountsHelp: "هەژمارەکە دەبێت پێشتر تۆمار کرابێت. پۆلەکەی هەڵبژێرە، پاشان دەتوانێت لەو پۆلەدا بڵاوبکاتەوە.",
        accountEmail: "ئیمەیڵی هەژمار",
        chooseCategory: "پۆلێک هەڵبژێرە",
        makeBusiness: "بیکە بە فرۆشگا",
        publicProducts: "کاڵا گشتییەکان",
        publicProductsHelp: "کاڵا بشارەوە ئەگەر دەتەوێت لە دۆزینەوە لابدات.",
        yourStore: "فرۆشگاکەت",
        category: "پۆل",
        acceptCardPayments: "وەرگرتنی پارە بە کارت",
        cardPaymentLinkHttps: "بەستەری پارەدان بە کارت، https://",
        cardNeverSees: "چاو کارتەکە نابینێت. کڕیار لەو بەستەرە پارە دەدات کە دەیلکێنیت.",
        saveStore: "پاشەکەوتکردنی فرۆشگا",
        addProduct: "زیادکردنی کاڵا",
        productName: "ناوی کاڵا",
        stockQuantity: "بڕی کۆگا",
        filters: "پاڵاوتن",
        productPhoto: "وێنەی کاڵا",
        publishProduct: "بڵاوکردنەوەی کاڵا",
        sales: "فرۆشتنەکان",
        thisMonthZero: "ئەم مانگە: 0",
        allSalesZero: "هەموو فرۆشتنەکان: 0",
        myProducts: "کاڵاکانم",
        chooseFilterWord: "وشەیەکی پاڵاوتن هەڵبژێرە",
        noFilterWordsYet: "بەڕێوەبەر هێشتا وشەی پاڵاوتنی زیاد نەکردووە.",
        photoTooLarge: "وێنەکە هێشتا گەورەیە. دانەیەکی بچووکتر هەڵبژێرە.",
        couldNotReadPhoto: "وێنەکە نەخوێندرایەوە.",
        chooseImageFile: "تکایە فایلێکی وێنە هەڵبژێرە.",
        imageUnder5: "وێنە دەبێت لە 5 مێگابایت کەمتر بێت.",
        chooseImageUnder5: "وێنەیەک هەڵبژێرە لە 5 مێگابایت کەمتر.",
        mustBeLoggedIn: "بۆ بڵاوکردنەوەی کاڵا دەبێت چووبیتە ژوورەوە.",
        fillProductFields: "تکایە هەموو خانەکانی کاڵا پڕ بکەرەوە.",
        productUpdated: "کاڵا نوێکرایەوە.",
        saveStoreBeforePublishing: "پێش بڵاوکردنەوە ناوی فرۆشگا پاشەکەوت بکە.",
        chooseOneFilter: "لانیکەم یەک پاڵاوتن بۆ ئەم کاڵایە هەڵبژێرە.",
        productPublished: "کاڵا بڵاوکرایەوە.",
        pleaseLogInProducts: "بچۆ ژوورەوە بۆ بینینی کاڵاکانت.",
        noProductsPublished: "هێشتا هیچ کاڵایەکت بڵاو نەکردووەتەوە.",
        quantitySold: "بڕی فرۆشراو",
        edit: "دەستکاری",
        recordSale: "تۆمارکردنی فرۆشتن",
        delete: "سڕینەوە",
        stockLabel: "کۆگا: {stock}",
        enterWholeNumber: "ژمارەیەکی تەواو بنووسە بۆ بڕی فرۆشراو.",
        cannotSellMore: "ناتوانیت زیاتر لە بڕی کۆگا بفرۆشیت.",
        saleRecorded: "فرۆشتن تۆمارکرا.",
        deleteThisProduct: "ئەم کاڵایە بسڕدرێتەوە؟",
        productDeleted: "کاڵا سڕایەوە.",
        couldNotLoadProducts: "کاڵاکان نەخوێندرانەوە.",
        thisMonth: "ئەم مانگە: {amount}",
        allSales: "هەموو فرۆشتنەکان: {amount}",
        noSalesYet: "هێشتا هیچ فرۆشتنێک تۆمار نەکراوە.",
        couldNotLoadSales: "فرۆشتنەکان نەخوێندرانەوە.",
        remove: "لابردن",
        noFilterWords: "هێشتا وشەی پاڵاوتن نییە.",
        noBusinessAccounts: "هێشتا هەژماری فرۆشگا نییە.",
        businessRemoved: "دەسەڵاتی فرۆشگا لابرا.",
        everyBusinessNamed: "هەموو فرۆشگاکان ناویان هەیە.",
        hasNotSavedStore: "{name} ناوی فرۆشگای پاشەکەوت نەکردووە.",
        noProductsYet: "هێشتا کاڵا نییە.",
        show: "پیشاندان",
        hide: "شاردنەوە",
        productPublicAgain: "کاڵا دیسان دەردەکەوێت.",
        productHidden: "کاڵا لە دۆزینەوە شاردرایەوە.",
        saveStoreThenPublish: "ناوی فرۆشگا پاشەکەوت بکە، پاشان لە هەژمارەکەتەوە بڵاوی بکەرەوە.",
        publishingAs: "بڵاوکردنەوە بە ناوی {name}.",
        typeFilterFirst: "سەرەتا وشەیەکی پاڵاوتن بنووسە.",
        filterExists: "ئەم وشەیە پێشتر هەیە.",
        filterWord: "وشەی پاڵاوتن",
        filterAlreadyInSection: "{word} پێشتر لە {section} دایە.",
        filterAdded: "وشەی پاڵاوتن زیادکرا.",
        typeEmailCategory: "ئیمەیڵ بنووسە و پۆلێک هەڵبژێرە.",
        adminStaysAdmin: "هەژماری بەڕێوەبەر بەڕێوەبەر دەمێنێتەوە.",
        noAccountEmail: "هێشتا هیچ هەژمارێکی تۆمارکراو ئەم ئیمەیڵە بەکارناهێنێت.",
        canPublishIn: "{email} دەتوانێت لە {category} بڵاوبکاتەوە.",
        enterTheStoreName: "ناوی فرۆشگا بنووسە.",
        adminMustGiveCategory: "بەڕێوەبەر دەبێت پۆلێک بەم هەژمارە بدات.",
        cardMustHttps: "بەستەری کارت دەبێت بە https:// دەست پێ بکات",
        cardLinkHttp: "بەستەری کارت دەبێت بە http:// یان https:// دەست پێ بکات",
        enterStoreName: "ناوی فرۆشگا بنووسە.",
        enterDisplayName: "ناوێکی پیشاندان بنووسە.",
        storeSaved: "فرۆشگا پاشەکەوتکرا.",
        accountSaved: "هەژمار پاشەکەوتکرا.",
        detailsSavedPiecesLater: "زانیارییەکانت پاشەکەوت کران. یاساکانی بنکەی دراوە بڵاوبکەرەوە تا پارچەکانیش نوێ ببنەوە.",
        saveStoreFirst: "سەرەتا ناوی فرۆشگا پاشەکەوت بکە.",
        enterNamePrice: "ناو و نرخ و وەسف بنووسە.",
        enterStock: "بڕی کۆگا بنووسە.",
        chooseFilter: "لانیکەم یەک پاڵاوتن هەڵبژێرە.",
        sectionSize: "قەبارە",
        sectionColor: "ڕەنگ",
        sectionType: "جۆر",
        sectionOther: "هیتر",
        chooseSection: "بەشێک هەڵبژێرە",
        newSection: "بەشی نوێ",
        sectionName: "ناوی بەش",
        chooseSectionFirst: "سەرەتا بەشێک هەڵبژێرە.",
        sectionSaveDenied: "یاساکانی بنکەی دراوە بڵاوبکەرەوە بۆ ئەوەی تاگ بچێتە ناو بەشێک.",
        wordEnglish: "ئینگلیزی",
        wordArabic: "عەرەبی",
        wordKurdish: "کوردی",
        sectionEnglish: "ناوی بەش بە ئینگلیزی",
        sectionArabic: "ناوی بەش بە عەرەبی",
        sectionKurdish: "ناوی بەش بە کوردی",
        browseBy: "بگەڕێ",
        jumpPieces: "پارچەکان",
        jumpOrders: "داواکارییەکان",
        jumpAdd: "پارچەیەک زیاد بکە",
        jumpDetails: "زانیاری",
        saveNeedsRules: "یاساکانی بنکەی دراوە بڵاوبکەرەوە، پاشان دووبارە هەوڵبدە.",
        pieceUpdated: "پارچە نوێکرایەوە.",
        publishedIn: "بڵاوکرایەوە لە {filters}.",
        noPiecesYet: "هێشتا هیچ پارچەیەکت بڵاو نەکردووەتەوە.",
        piecePhoto: "وێنەی پارچە",
        piece: "پارچە",
        inStockLabel: "لە کۆگا: {stock}",
        editThisPiece: "دەستکاریی ئەم پارچەیە",
        saveChanges: "پاشەکەوتکردنی گۆڕانکاری",
        deleteThisPiece: "ئەم پارچەیە بسڕدرێتەوە؟",
        couldNotLoadPieces: "پارچەکانت نەخوێندرانەوە.",
        all: "هەموو",
        nothingMatches: "هیچ شتێک لەگەڵ ئەم گەڕانە ناگونجێت.",
        closestMatches: "نزیکترین لە گەڕانەکەت",
        nothingInCategory: "هێشتا هیچ شتێک لەم پۆلەدا نییە.",
        putInCart: "بیخە ناو سەبەتە",
        chooseOptions: "ڕەنگ و قەبارە هەڵبژێرە",
        chooseColorAndSize: "ڕەنگ و قەبارە هەڵبژێرە.",
        chooseColorFirst: "ڕەنگێک هەڵبژێرە.",
        chooseSizeFirst: "قەبارەیەک هەڵبژێرە.",
        signInToBuy: "بچۆ ژوورەوە بۆ کڕین",
        store: "فرۆشگا",
        product: "کاڵا",
        callStore: "پەیوەندی بە فرۆشگا",
        whatsapp: "واتساپ",
        whatsappHello: "سڵاو، {product}م دەوێت لە {store}.",
        whatsappCard: "دەمەوێت بە کارت پارەی {product} بدەم.",
        cardContact: "ئەم فرۆشگایە پارەدان بە کارت وەردەگرێت. بۆ پارەدان پەیوەندی بە فرۆشگا بکە.",
        productMissing: "ئەم کاڵایە نەدۆزرایەوە.",
        productUnavailable: "ئەم کاڵایە بەردەست نییە.",
        productOpenFailed: "ئەم کاڵایە نەکرایەوە.",
        inStock: "لە کۆگا: {stock}",
        signInToBuyPeriod: "بچۆ ژوورەوە بۆ کڕین.",
        outOfStock: "لە کۆگا نەماوە.",
        onlyLeft: "تەنها {stock} ماوە.",
        addedToCart: "خرایە ناو سەبەتە.",
        cartEmpty: "سەبەتەکەت بەتاڵە.",
        pieceWord: "پارچە",
        piecesWord: "پارچە",
        totalLine: "{count} {pieces} · کۆ {amount}",
        clothesLine: "جلوبەرگ {amount}",
        clothesCardLine: "جلوبەرگ {amount}. پارەی فرۆشگا لە بەستەری کارتەکەی بدە.",
        deliveryLine: "گەیاندن {amount}",
        payDriverDoor: "پارەی گەیەنەر لە دەرگا بدە {amount}",
        driverFees: "\nجلوبەرگ: {clothes}\nگەیاندن: {delivery}\nکاش لە دەرگا: {cash}",
        signInToBuyLocation: "بچۆ ژوورەوە بۆ کڕین. شوێنی گەیاندن لە هەژمارەکەتدا پاشەکەوت دەکرێت.",
        deliverTo: "بیگەیەنە بۆ: {location}",
        addLocationBefore: "پێش ناردنی داواکاری شوێنی گەیاندن لە هەژمارەکەت زیاد بکە.",
        noOrders: "هێشتا داواکاری نییە.",
        signInToSeeOrders: "بچۆ ژوورەوە بۆ بینینی داواکارییەکانت.",
        statusLine: "دۆخ: {status}",
        ordersAfterRules: "داواکارییەکان دوای بڵاوکردنەوەی یاساکانی بنکەی دراوە دەردەکەون.",
        newOrderFrom: "داواکارییەکی نوێ لە {name}. بیگەیەنە بۆ {location}.",
        aCustomer: "کڕیارێک",
        theirSavedAddress: "ناونیشانە پاشەکەوتکراوەکەی",
        newOrdersWaiting: "{count} داواکاریی نوێ چاوەڕێن.",
        openOrders: "کردنەوەی داواکاری",
        markSeen: "وەک بینراو",
        newChawOrder: "داواکارییەکی نوێی چاو",
        aCustomerCap: "کڕیارێک",
        theirAddress: "ناونیشانەکەی",
        orderedDeliver: "{name} داوای {items}ی کرد. بیگەیەنە بۆ {location}.",
        onTheWay: "لە ڕێگەدایە",
        delivered: "گەیەندرا",
        statusNew: "نوێ",
        statusCancelled: "هەڵوەشاوە",
        cancelOrder: "هەڵوەشاندنەوەی داواکاری",
        customerNameLine: "ناوی کڕیار: {name}",
        sizeLine: "قەبارە: {size}",
        colorLine: "ڕەنگ: {color}",
        quantityLine: "بڕ: {count}",
        priceLine: "نرخ: {price}",
        couldNotCancel: "ئەم داواکارییە هەڵنەوەشایەوە.",
        markDelivered: "وەک گەیەندراو",
        customer: "کڕیار",
        phoneLine: "تەلەفۆن: {phone}",
        yourCartEmpty: "سەبەتەکەت بەتاڵە.",
        saveLocationFirst: "هەژمارەکەت بکەرەوە و سەرەتا شوێنی گەیاندن پاشەکەوت بکە.",
        savePhoneFirst: "هەژمارەکەت بکەرەوە و سەرەتا ژمارەی تەلەفۆن پاشەکەوت بکە.",
        addPhoneBefore: "پێش ناردنی داواکاری ژمارەی تەلەفۆن لە هەژمارەکەت زیاد بکە.",
        openInMaps: "کردنەوە لە نەخشە",
        callCustomer: "پەیوەندی",
        sendToDriver: "ناردن بۆ گەیەنەر",
        addDriverNumber: "ژمارەی واتساپی گەیەنەر لە پەیوەندی فرۆشگا زیاد بکە.",
        noPhone: "تەلەفۆن نییە",
        driverOrder: "گەیاندنی نوێ\n{name}\nتەلەفۆن: {phone}\nناونیشان: {location}\n{pin}{items}\n{payment}{fees}",
        shareLocationText: "شوێنەکەت بکەرەوە تا فرۆشگا گەیەنەر بنێرێت بۆ هەمان شوێن.",
        useMyLocation: "شوێنەکەم بەکاربهێنە",
        notNow: "ئێستا نا",
        findingLocation: "شوێنەکەت دەدۆزرێتەوە…",
        locationSaved: "شوێنی ورد پاشەکەوت کرا. فرۆشگا دەتوانێت ئەم خاڵە بنێرێت بۆ گەیەنەر.",
        locationDenied: "شوێنەکە داخراو مایەوە. لە وێبگەڕەکە دایبگیرسێنە و دووبارە هەوڵبدە.",
        locationFailed: "شوێنەکەت نەخوێندرایەوە. دووبارە هەوڵبدە.",
        locationUnsupported: "ئەم وێبگەڕە ناتوانێت شوێن هاوبەش بکات.",
        pinLine: "خاڵ: {url}",
        exactPinSaved: "شوێنی ورد پاشەکەوت کرا.",
        pieceHasNoStore: "پارچەیەک فرۆشگای نییە، بۆیە ناتوانرێت داوا بکرێت.",
        aPiece: "پارچەیەک",
        noLongerAvailable: "{name} چیتر بەردەست نییە.",
        onlyLeftOf: "تەنها {stock} لە {name} ماوە.",
        theStore: "فرۆشگا",
        orderSentCard: "داواکاری نێردرا. پارەکە بە کارت لەگەڵ فرۆشگا بدە.",
        orderSentDelivery: "داواکاری نێردرا. پارەدان لە کاتی گەیاندن. فرۆشگا ناونیشانەکەتی هەیە.",
        payStoreByCard: "پارەی {store} بە کارت بدە",
        publishRulesStock: "یاسا نوێیەکانی بنکەی دراوە بڵاوبکەرەوە بۆ ئەوەی کۆگا دابەزێت، پاشان دووبارە هەوڵبدە.",
        couldNotPlaceOrder: "داواکاری نەنێردرا.",
        inCategory: " لە {category}",
        noCategoryYet: " — هێشتا پۆلی نییە",
        hiddenTag: " (شاراوە)"
    }
};

const listeners = [];
let currentLang = detectLanguage();

function detectLanguage() {
    const saved = localStorage.getItem(STORAGE_KEY);

    if (saved === "en" || saved === "ar" || saved === "ckb") {
        return saved;
    }

    const list = navigator.languages && navigator.languages.length
        ? navigator.languages
        : [navigator.language || "en"];

    for (const item of list) {
        const tag = String(item).toLowerCase();

        if (tag === "ckb" || tag.startsWith("ku")) {
            return "ckb";
        }

        if (tag.startsWith("ar")) {
            return "ar";
        }
    }

    return "en";
}

export function t(key, vars) {
    const pack = phrases[currentLang] || phrases.en;
    let text = pack[key] || phrases.en[key] || key;

    if (vars) {
        Object.keys(vars).forEach((name) => {
            text = text.split("{" + name + "}").join(String(vars[name]));
        });
    }

    return text;
}

export function onLanguageChange(listener) {
    listeners.push(listener);
}

export function applyLanguage() {
    const rtl = currentLang === "ar" || currentLang === "ckb";
    document.documentElement.lang = currentLang;
    document.documentElement.dir = rtl ? "rtl" : "ltr";

    document.querySelectorAll("[data-i18n]").forEach((element) => {
        element.textContent = t(element.dataset.i18n);
    });

    document.querySelectorAll("[data-i18n-html]").forEach((element) => {
        element.innerHTML = t(element.dataset.i18nHtml);
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
        element.placeholder = t(element.dataset.i18nPlaceholder);
    });

    document.querySelectorAll("[data-i18n-aria]").forEach((element) => {
        element.setAttribute("aria-label", t(element.dataset.i18nAria));
    });

    const titleKey = document.documentElement.dataset.i18nTitle;

    if (titleKey) {
        document.title = t(titleKey);
    }

    document.querySelectorAll(".lang-switch button").forEach((button) => {
        button.setAttribute("aria-pressed", button.dataset.lang === currentLang ? "true" : "false");
    });
}

export function setLanguage(lang, remember) {
    if (lang !== "en" && lang !== "ar" && lang !== "ckb") {
        return;
    }

    currentLang = lang;

    if (remember) {
        localStorage.setItem(STORAGE_KEY, lang);
    }

    applyLanguage();
    listeners.forEach((listener) => listener(lang));
}

function setupSwitcher() {
    const nav = document.querySelector("nav");

    if (!nav || document.querySelector(".lang-switch")) {
        return;
    }

    const group = document.createElement("div");
    group.className = "lang-switch";
    group.setAttribute("role", "group");

    [
        ["en", "English"],
        ["ar", "العربية"],
        ["ckb", "کوردی"]
    ].forEach(([code, label]) => {
        const button = document.createElement("button");
        button.type = "button";
        button.dataset.lang = code;
        button.textContent = label;
        button.addEventListener("click", () => setLanguage(code, true));
        group.appendChild(button);
    });

    const join = document.getElementById("join-link");

    if (join) {
        nav.insertBefore(group, join);
    } else {
        nav.appendChild(group);
    }
}

setupSwitcher();
applyLanguage();
